SELECT A.ID, IFNULL(B.CHILD,0) AS CHILD_COUNT
FROM ECOLI_DATA A LEFT JOIN (SELECT PARENT_ID, COUNT(ID) AS CHILD
                             FROM ECOLI_DATA
                             GROUP BY PARENT_ID) B ON A.ID = B.PARENT_ID