SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY,' ',B.STREET_ADDRESS1,' ',B.STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(TLNO,3),'-',MID(TLNO,4,4),'-',RIGHT(TLNO,4)) AS 전화번호
FROM (SELECT WRITER_ID
      FROM USED_GOODS_BOARD 
      GROUP BY WRITER_ID
      HAVING COUNT(BOARD_ID) >= 3 )AS A JOIN USED_GOODS_USER AS B
ON A.WRITER_ID = B.USER_ID
ORDER BY 1 DESC