WITH RECURSIVE 
GEN AS(
    SELECT ID,PARENT_ID,1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
UNION ALL
    SELECT A.ID,A.PARENT_ID, B.GENERATION + 1
    FROM ECOLI_DATA A JOIN GEN B
        ON A.PARENT_ID = B.ID
),
GEN_NO_CHILD AS (
    SELECT C.ID, C.GENERATION
    FROM GEN C LEFT JOIN ECOLI_DATA D
    ON C.ID = D.PARENT_ID
    WHERE D.ID IS NULL
)

SELECT COUNT(ID) COUNT, GENERATION
FROM GEN_NO_CHILD
GROUP BY 2
ORDER BY 2;