SELECT X.FLAVOR
FROM FIRST_HALF AS X RIGHT JOIN 
(SELECT A.SHIPMENT_ID, A.FLAVOR, (A.TOTAL_ORDER+B.TOTAL_ORDER)AS TOTAL_ORDER
FROM (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM FIRST_HALF
     GROUP BY FLAVOR)AS A 
      JOIN (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
           GROUP BY FLAVOR)AS B 
ON A.SHIPMENT_ID = B.SHIPMENT_ID
GROUP BY A.FLAVOR
ORDER BY TOTAL_ORDER DESC
LIMIT 3
) AS Y
ON X.SHIPMENT_ID = Y.SHIPMENT_ID
WHERE X.FLAVOR IS NOT NULL
