SELECT Y.EMP_NO, Y.EMP_NAME, Y.GRADE, CASE
WHEN GRADE LIKE 'S' THEN (Y.SAL*20)/100
WHEN GRADE LIKE 'A' THEN (Y.SAL*15)/100
WHEN GRADE LIKE 'B' THEN (Y.SAL*10)/100
ELSE SAL*0 END AS BONUS
FROM (SELECT B.SAL, B.EMP_NO, B.EMP_NAME,
    CASE
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C' END AS GRADE
    FROM HR_GRADE A JOIN HR_EMPLOYEES B
    ON A.EMP_NO = B.EMP_NO
    GROUP BY EMP_NO
    ) Y
ORDER BY 1;