SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO A LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID 
    JOIN ITEM_INFO C ON B.ITEM_ID = C.ITEM_ID
WHERE A.RARITY IN ('RARE')
ORDER BY 1 DESC;
