# 총 대여 횟수가 5회 이상인 CAR_ID와 대여횟수를 찾는 테이블 만들기
# 찾은 CAR_ID들의 월 별 대여횟수 구하기
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' AND CAR_ID IN (SELECT CAR_ID 
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                 GROUP BY CAR_ID
                 HAVING COUNT(HISTORY_ID) >= 5
                 )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY 1 ASC, 2 DESC;