SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM(SELECT COUNT(ID) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE, AVG(IFNULL(LENGTH,10)) LNAVG
FROM FISH_INFO
GROUP BY FISH_TYPE) A
WHERE A.LNAVG>=33
ORDER BY 3;

